# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# Turn into nparrays
np_height = np.array(height)
np_weight = np.array(weight)

# Calculate bmi
bmi = np_weight/(np_height**2) * 730

print(bmi)

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]




[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


[0.74 0.16 0.69 0.49 0.95]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [21]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

def makeMatrix(x,y,z):
    random_matrix = np.random.rand(x,y,z)
    return print(random_matrix)

makeMatrix(3,4,4)



[[[0.64512857 0.74301484 0.1198435  0.26562692]
  [0.40632551 0.63900196 0.58398786 0.15933674]
  [0.42309468 0.43148392 0.77578837 0.05494249]
  [0.44044693 0.3768198  0.78227656 0.03006543]]

 [[0.50186681 0.67066248 0.16633552 0.29502432]
  [0.09500171 0.81530452 0.95772925 0.75310588]
  [0.89778304 0.12604993 0.2154569  0.13633126]
  [0.41737865 0.27799753 0.29084828 0.51342373]]

 [[0.17329608 0.16341196 0.86626031 0.78482448]
  [0.85565269 0.038006   0.23270403 0.21348612]
  [0.70586045 0.76150896 0.5146465  0.97471476]
  [0.39873918 0.65184751 0.31964025 0.30787972]]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [31]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d=','):
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        info = csv.reader(mData,delimeter=d)
        
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('./redsox_2017_hitting.csv')



FileNotFoundError: [Errno 2] No such file or directory: '../redsox_2017_hitting.csv'

In [34]:
import csv 
import numpy as np
import statistics

"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

# Grab mean of statistics
#     Compare 2018 against 2017

slg_2017 = statistics.mean(bs2017['SLG'])
slg_2018 = statistics.mean(bs2018['SLG'])

if slg_2017 > slg_2018:
    print('The SLG of 2017 was higher than that of 2018')
else:
    print('The SLG of 2018 was higher than that of 2017')

The SLG of 2017 was higher than that of 2018
